//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for ActionStateT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActionStateT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Created"/>
 *     &lt;enumeration value="Running"/>
 *     &lt;enumeration value="Aborting"/>
 *     &lt;enumeration value="TimeDelay"/>
 *     &lt;enumeration value="WaitingForFeedback"/>
 *     &lt;enumeration value="TimeDelayA"/>
 *     &lt;enumeration value="WaitingForFeedbackA"/>
 *     &lt;enumeration value="Aborted"/>
 *     &lt;enumeration value="Completed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ActionStateT")
@XmlEnum
public enum ActionStateT {


    /**
     * The Action has been created.
     * 
     */
    @XmlEnumValue("Created")
    CREATED("Created"),

    /**
     * The Action is running.
     * 
     */
    @XmlEnumValue("Running")
    RUNNING("Running"),

    /**
     * The Action has been aborting and abort processing is in progress.
     * 
     */
    @XmlEnumValue("Aborting")
    ABORTING("Aborting"),

    /**
     * The Action is delayed.
     * 
     */
    @XmlEnumValue("TimeDelay")
    TIME_DELAY("TimeDelay"),

    /**
     * The Action is waiting for user feedback.
     * 
     */
    @XmlEnumValue("WaitingForFeedback")
    WAITING_FOR_FEEDBACK("WaitingForFeedback"),

    /**
     * The Action is delayed during abort processing.
     * 
     */
    @XmlEnumValue("TimeDelayA")
    TIME_DELAY_A("TimeDelayA"),

    /**
     * The Action is waiting for user feedback during abort processing.
     * 
     */
    @XmlEnumValue("WaitingForFeedbackA")
    WAITING_FOR_FEEDBACK_A("WaitingForFeedbackA"),

    /**
     * The Action has been aborted and abort processing is complete.
     * 
     */
    @XmlEnumValue("Aborted")
    ABORTED("Aborted"),

    /**
     * The Action has terminated normally.
     * 
     */
    @XmlEnumValue("Completed")
    COMPLETED("Completed");
    private final String value;

    ActionStateT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ActionStateT fromValue(String v) {
        for (ActionStateT c: ActionStateT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
