//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for ActionRequestT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ActionRequestT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ActionState" type="{http://fdi.org/2010/client}ActionStateT"/>
 *         &lt;choice>
 *           &lt;element name="AcknowledgementRequest" type="{http://fdi.org/2010/client}AcknowledgementRequestT"/>
 *           &lt;element name="AbortRequest" type="{http://fdi.org/2010/client}AbortRequestT"/>
 *           &lt;element name="UIDRequest" type="{http://fdi.org/2010/client}UidRequestT"/>
 *           &lt;element name="SelectionRequest" type="{http://fdi.org/2010/client}SelectionRequestT"/>
 *           &lt;element name="InputRequest" type="{http://fdi.org/2010/client}InputRequestT"/>
 *           &lt;element name="InfoRequest" type="{http://fdi.org/2010/client}InfoRequestT"/>
 *           &lt;element name="DelayMessageRequest" type="{http://fdi.org/2010/client}DelayMessageRequestT"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ActionRequestT", propOrder = {
    "actionState",
    "acknowledgementRequest",
    "abortRequest",
    "uidRequest",
    "selectionRequest",
    "inputRequest",
    "infoRequest",
    "delayMessageRequest"
})
public class ActionRequestT {

    @XmlElement(name = "ActionState", required = true)
    protected ActionStateT actionState;
    @XmlElement(name = "AcknowledgementRequest")
    protected AcknowledgementRequestT acknowledgementRequest;
    @XmlElement(name = "AbortRequest")
    protected AbortRequestT abortRequest;
    @XmlElement(name = "UIDRequest")
    protected UidRequestT uidRequest;
    @XmlElement(name = "SelectionRequest")
    protected SelectionRequestT selectionRequest;
    @XmlElement(name = "InputRequest")
    protected InputRequestT inputRequest;
    @XmlElement(name = "InfoRequest")
    protected InfoRequestT infoRequest;
    @XmlElement(name = "DelayMessageRequest")
    protected DelayMessageRequestT delayMessageRequest;

    /**
     * Gets the value of the actionState property.
     * 
     * @return
     *     possible object is
     *     {@link ActionStateT }
     *     
     */
    public ActionStateT getActionState() {
        return actionState;
    }

    /**
     * Sets the value of the actionState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionStateT }
     *     
     */
    public void setActionState(ActionStateT value) {
        this.actionState = value;
    }

    /**
     * Gets the value of the acknowledgementRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AcknowledgementRequestT }
     *     
     */
    public AcknowledgementRequestT getAcknowledgementRequest() {
        return acknowledgementRequest;
    }

    /**
     * Sets the value of the acknowledgementRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AcknowledgementRequestT }
     *     
     */
    public void setAcknowledgementRequest(AcknowledgementRequestT value) {
        this.acknowledgementRequest = value;
    }

    /**
     * Gets the value of the abortRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AbortRequestT }
     *     
     */
    public AbortRequestT getAbortRequest() {
        return abortRequest;
    }

    /**
     * Sets the value of the abortRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbortRequestT }
     *     
     */
    public void setAbortRequest(AbortRequestT value) {
        this.abortRequest = value;
    }

    /**
     * Gets the value of the uidRequest property.
     * 
     * @return
     *     possible object is
     *     {@link UidRequestT }
     *     
     */
    public UidRequestT getUIDRequest() {
        return uidRequest;
    }

    /**
     * Sets the value of the uidRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link UidRequestT }
     *     
     */
    public void setUIDRequest(UidRequestT value) {
        this.uidRequest = value;
    }

    /**
     * Gets the value of the selectionRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionRequestT }
     *     
     */
    public SelectionRequestT getSelectionRequest() {
        return selectionRequest;
    }

    /**
     * Sets the value of the selectionRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionRequestT }
     *     
     */
    public void setSelectionRequest(SelectionRequestT value) {
        this.selectionRequest = value;
    }

    /**
     * Gets the value of the inputRequest property.
     * 
     * @return
     *     possible object is
     *     {@link InputRequestT }
     *     
     */
    public InputRequestT getInputRequest() {
        return inputRequest;
    }

    /**
     * Sets the value of the inputRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputRequestT }
     *     
     */
    public void setInputRequest(InputRequestT value) {
        this.inputRequest = value;
    }

    /**
     * Gets the value of the infoRequest property.
     * 
     * @return
     *     possible object is
     *     {@link InfoRequestT }
     *     
     */
    public InfoRequestT getInfoRequest() {
        return infoRequest;
    }

    /**
     * Sets the value of the infoRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link InfoRequestT }
     *     
     */
    public void setInfoRequest(InfoRequestT value) {
        this.infoRequest = value;
    }

    /**
     * Gets the value of the delayMessageRequest property.
     * 
     * @return
     *     possible object is
     *     {@link DelayMessageRequestT }
     *     
     */
    public DelayMessageRequestT getDelayMessageRequest() {
        return delayMessageRequest;
    }

    /**
     * Sets the value of the delayMessageRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link DelayMessageRequestT }
     *     
     */
    public void setDelayMessageRequest(DelayMessageRequestT value) {
        this.delayMessageRequest = value;
    }

}
