//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for ChartTypeT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChartTypeT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Gauge"/>
 *     &lt;enumeration value="HorizontalBar"/>
 *     &lt;enumeration value="Scope"/>
 *     &lt;enumeration value="Strip"/>
 *     &lt;enumeration value="Sweep"/>
 *     &lt;enumeration value="VerticalBar"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChartTypeT")
@XmlEnum
public enum ChartTypeT {


    /**
     * A single source value is displayed as a gauge, which is a graphical representation similar to the fuel gauge in an automobile.
     * 
     */
    @XmlEnumValue("Gauge")
    GAUGE("Gauge"),

    /**
     * The source values are displayed as horizontal bars.
     * 
     */
    @XmlEnumValue("HorizontalBar")
    HORIZONTAL_BAR("HorizontalBar"),

    /**
     * The source values are displayed as a curve moving from left to right. When the source values reaches the far right of the display area, the display area is erased and the new source values are displayed beginning at the far left.
     * 
     */
    @XmlEnumValue("Scope")
    SCOPE("Scope"),

    /**
     * The source values are displayed as a curve moving from left to right. When the source values reach the far right of the display area, the display area is scrolled with the source values on the far left being removed and the new source values being displayed on the right.
     * 
     */
    @XmlEnumValue("Strip")
    STRIP("Strip"),

    /**
     * The source values are displayed as a curve moving from left to right. When the source values reach the far right of the display area, the new source values are displayed beginning at the far left, but unlike Scope only the portion of the display area needed to display the new source values is erased.
     * 
     */
    @XmlEnumValue("Sweep")
    SWEEP("Sweep"),

    /**
     * The source values are displayed as vertical bars.
     * 
     */
    @XmlEnumValue("VerticalBar")
    VERTICAL_BAR("VerticalBar");
    private final String value;

    ChartTypeT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChartTypeT fromValue(String v) {
        for (ChartTypeT c: ChartTypeT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
