//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for DateTimeDataT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DateTimeDataT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Date"/>
 *     &lt;enumeration value="Time"/>
 *     &lt;enumeration value="DateTime"/>
 *     &lt;enumeration value="Duration"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DateTimeDataT")
@XmlEnum
public enum DateTimeDataT {


    /**
     * A value that represents a date without a time.
     * 
     */
    @XmlEnumValue("Date")
    DATE("Date"),

    /**
     * A value that represents a time without a date.
     * 
     */
    @XmlEnumValue("Time")
    TIME("Time"),

    /**
     * A value that represents a date and time.
     * 
     */
    @XmlEnumValue("DateTime")
    DATE_TIME("DateTime"),

    /**
     * A value that represents a length of time.
     * 
     */
    @XmlEnumValue("Duration")
    DURATION("Duration");
    private final String value;

    DateTimeDataT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DateTimeDataT fromValue(String v) {
        for (DateTimeDataT c: DateTimeDataT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
