//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import java.math.BigInteger;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlSchemaType;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * This type specifies a request sent from an FDI Server to an FDI Client when a delay occurs within an Action. The FDI Client informs the user of the reason for the delay and expected duration of the delay. The FDI Client then sends a ActionResponse back to the FDI Server. The FDI Server may send DelayMessageRequests frequently with updated information regarding the length of the delay. When the delay is finished, the FDI Server sends a DelayMessageRequest with the SecondsToWait element set to zero.
 * 
 * <p>Java class for DelayMessageRequestT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DelayMessageRequestT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SecondsToWait" type="{http://www.w3.org/2001/XMLSchema}unsignedLong"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DelayMessageRequestT", propOrder = {
    "message",
    "secondsToWait"
})
public class DelayMessageRequestT {

    @XmlElement(name = "Message", required = true)
    protected String message;
    @XmlElement(name = "SecondsToWait", required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger secondsToWait;

    /**
     * Gets the value of the message property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMessage() {
        return message;
    }

    /**
     * Sets the value of the message property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMessage(String value) {
        this.message = value;
    }

    /**
     * Gets the value of the secondsToWait property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSecondsToWait() {
        return secondsToWait;
    }

    /**
     * Sets the value of the secondsToWait property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSecondsToWait(BigInteger value) {
        this.secondsToWait = value;
    }

}
