//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * The type specifies a collection of parameters that should presented to the user at the same time.
 * 
 * <p>Java class for EditDisplayT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EditDisplayT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}LayoutObjectT">
 *       &lt;sequence>
 *         &lt;element name="DisplayItemList" type="{http://fdi.org/2010/client}ParameterListT" minOccurs="0"/>
 *         &lt;element name="EditItemList" type="{http://fdi.org/2010/client}ParameterListT"/>
 *         &lt;element name="PreEditActionList" type="{http://fdi.org/2010/client}ActionListT" minOccurs="0"/>
 *         &lt;element name="PostEditActionList" type="{http://fdi.org/2010/client}ActionListT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EditDisplayT", propOrder = {
    "displayItemList",
    "editItemList",
    "preEditActionList",
    "postEditActionList"
})
public class EditDisplayT
    extends LayoutObjectT
{

    @XmlElement(name = "DisplayItemList")
    protected ParameterListT displayItemList;
    @XmlElement(name = "EditItemList", required = true)
    protected ParameterListT editItemList;
    @XmlElement(name = "PreEditActionList")
    protected ActionListT preEditActionList;
    @XmlElement(name = "PostEditActionList")
    protected ActionListT postEditActionList;

    /**
     * Gets the value of the displayItemList property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterListT }
     *     
     */
    public ParameterListT getDisplayItemList() {
        return displayItemList;
    }

    /**
     * Sets the value of the displayItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterListT }
     *     
     */
    public void setDisplayItemList(ParameterListT value) {
        this.displayItemList = value;
    }

    /**
     * Gets the value of the editItemList property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterListT }
     *     
     */
    public ParameterListT getEditItemList() {
        return editItemList;
    }

    /**
     * Sets the value of the editItemList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterListT }
     *     
     */
    public void setEditItemList(ParameterListT value) {
        this.editItemList = value;
    }

    /**
     * Gets the value of the preEditActionList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionListT }
     *     
     */
    public ActionListT getPreEditActionList() {
        return preEditActionList;
    }

    /**
     * Sets the value of the preEditActionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionListT }
     *     
     */
    public void setPreEditActionList(ActionListT value) {
        this.preEditActionList = value;
    }

    /**
     * Gets the value of the postEditActionList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionListT }
     *     
     */
    public ActionListT getPostEditActionList() {
        return postEditActionList;
    }

    /**
     * Sets the value of the postEditActionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionListT }
     *     
     */
    public void setPostEditActionList(ActionListT value) {
        this.postEditActionList = value;
    }

}
