//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import java.math.BigInteger;
import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlSchemaType;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * This type specifies a graph that graphically displays a finite data set from a device.
 * 
 * <p>Java class for GraphT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GraphT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}LayoutObjectExtT">
 *       &lt;sequence>
 *         &lt;element name="Height" type="{http://fdi.org/2010/client}SizeT" minOccurs="0"/>
 *         &lt;element name="Width" type="{http://fdi.org/2010/client}SizeT" minOccurs="0"/>
 *         &lt;element name="CycleTime" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *         &lt;element name="HorizontalAxis" type="{http://fdi.org/2010/client}AxisT"/>
 *         &lt;element name="WaveformList" type="{http://fdi.org/2010/client}WaveformListT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GraphT", propOrder = {
    "height",
    "width",
    "cycleTime",
    "horizontalAxis",
    "waveformList"
})
public class GraphT
    extends LayoutObjectExtT
{

    @XmlElement(name = "Height")
    protected SizeT height;
    @XmlElement(name = "Width")
    protected SizeT width;
    @XmlElement(name = "CycleTime")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger cycleTime;
    @XmlElement(name = "HorizontalAxis", required = true)
    protected AxisT horizontalAxis;
    @XmlElement(name = "WaveformList", required = true)
    protected WaveformListT waveformList;

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link SizeT }
     *     
     */
    public SizeT getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeT }
     *     
     */
    public void setHeight(SizeT value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link SizeT }
     *     
     */
    public SizeT getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeT }
     *     
     */
    public void setWidth(SizeT value) {
        this.width = value;
    }

    /**
     * Gets the value of the cycleTime property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCycleTime() {
        return cycleTime;
    }

    /**
     * Sets the value of the cycleTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCycleTime(BigInteger value) {
        this.cycleTime = value;
    }

    /**
     * Gets the value of the horizontalAxis property.
     * 
     * @return
     *     possible object is
     *     {@link AxisT }
     *     
     */
    public AxisT getHorizontalAxis() {
        return horizontalAxis;
    }

    /**
     * Sets the value of the horizontalAxis property.
     * 
     * @param value
     *     allowed object is
     *     {@link AxisT }
     *     
     */
    public void setHorizontalAxis(AxisT value) {
        this.horizontalAxis = value;
    }

    /**
     * Gets the value of the waveformList property.
     * 
     * @return
     *     possible object is
     *     {@link WaveformListT }
     *     
     */
    public WaveformListT getWaveformList() {
        return waveformList;
    }

    /**
     * Sets the value of the waveformList property.
     * 
     * @param value
     *     allowed object is
     *     {@link WaveformListT }
     *     
     */
    public void setWaveformList(WaveformListT value) {
        this.waveformList = value;
    }

}
