//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HandlingT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="HandlingT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ro"/>
 *     &lt;enumeration value="wo"/>
 *     &lt;enumeration value="rw"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "HandlingT")
@XmlEnum
public enum HandlingT {


    /**
     * The item may only be read.
     * 
     */
    @XmlEnumValue("ro")
    RO("ro"),

    /**
     * The item may only be written.
     * 
     */
    @XmlEnumValue("wo")
    WO("wo"),

    /**
     * The item may be read or written.
     * 
     */
    @XmlEnumValue("rw")
    RW("rw");
    private final String value;

    HandlingT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static HandlingT fromValue(String v) {
        for (HandlingT c: HandlingT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
