//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * This type specifies a visual entity such as a picture or illustration.
 * 
 * <p>Java class for ImageT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ImageT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}LayoutObjectExtT">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Format" type="{http://fdi.org/2010/client}ImageFormatT"/>
 *         &lt;element name="Height" type="{http://fdi.org/2010/client}SizeT"/>
 *         &lt;element name="Width" type="{http://fdi.org/2010/client}SizeT"/>
 *         &lt;element name="Inline" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Link" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://fdi.org/2010/client}LayoutItemsT">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;choice>
 *                     &lt;element name="Window" type="{http://fdi.org/2010/client}WindowT"/>
 *                     &lt;element name="Dialog" type="{http://fdi.org/2010/client}DialogT"/>
 *                     &lt;element name="Page" type="{http://fdi.org/2010/client}PageT"/>
 *                     &lt;element name="Group" type="{http://fdi.org/2010/client}GroupT"/>
 *                     &lt;element name="Menu" type="{http://fdi.org/2010/client}MenuT"/>
 *                     &lt;element name="Table" type="{http://fdi.org/2010/client}TableT"/>
 *                     &lt;element name="Plugin" type="{http://fdi.org/2010/client}PluginT"/>
 *                     &lt;element name="Action" type="{http://fdi.org/2010/client}ActionT"/>
 *                   &lt;/choice>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ImageT", propOrder = {
    "name",
    "format",
    "height",
    "width",
    "inline",
    "link"
})
public class ImageT
    extends LayoutObjectExtT
{

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Format", required = true)
    protected ImageFormatT format;
    @XmlElement(name = "Height", required = true)
    protected SizeT height;
    @XmlElement(name = "Width", required = true)
    protected SizeT width;
    @XmlElement(name = "Inline", defaultValue = "false")
    protected Boolean inline;
    @XmlElement(name = "Link")
    protected ImageT.Link link;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the format property.
     * 
     * @return
     *     possible object is
     *     {@link ImageFormatT }
     *     
     */
    public ImageFormatT getFormat() {
        return format;
    }

    /**
     * Sets the value of the format property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageFormatT }
     *     
     */
    public void setFormat(ImageFormatT value) {
        this.format = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link SizeT }
     *     
     */
    public SizeT getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeT }
     *     
     */
    public void setHeight(SizeT value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link SizeT }
     *     
     */
    public SizeT getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeT }
     *     
     */
    public void setWidth(SizeT value) {
        this.width = value;
    }

    /**
     * Gets the value of the inline property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInline() {
        return inline;
    }

    /**
     * Sets the value of the inline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInline(Boolean value) {
        this.inline = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link ImageT.Link }
     *     
     */
    public ImageT.Link getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageT.Link }
     *     
     */
    public void setLink(ImageT.Link value) {
        this.link = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://fdi.org/2010/client}LayoutItemsT">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;choice>
     *           &lt;element name="Window" type="{http://fdi.org/2010/client}WindowT"/>
     *           &lt;element name="Dialog" type="{http://fdi.org/2010/client}DialogT"/>
     *           &lt;element name="Page" type="{http://fdi.org/2010/client}PageT"/>
     *           &lt;element name="Group" type="{http://fdi.org/2010/client}GroupT"/>
     *           &lt;element name="Menu" type="{http://fdi.org/2010/client}MenuT"/>
     *           &lt;element name="Table" type="{http://fdi.org/2010/client}TableT"/>
     *           &lt;element name="Plugin" type="{http://fdi.org/2010/client}PluginT"/>
     *           &lt;element name="Action" type="{http://fdi.org/2010/client}ActionT"/>
     *         &lt;/choice>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Link
        extends LayoutItemsT
    {


    }

}
