//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for ImageFormatT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ImageFormatT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GIF"/>
 *     &lt;enumeration value="JPG"/>
 *     &lt;enumeration value="PNG"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ImageFormatT")
@XmlEnum
public enum ImageFormatT {


    /**
     * The Graphics Interchange Format.
     * 
     */
    GIF,

    /**
     * The Joint Photographic Experts Group File Interchange Format.
     * 
     */
    JPG,

    /**
     * The Portable Network Graphics format.
     * 
     */
    PNG;

    public String value() {
        return name();
    }

    public static ImageFormatT fromValue(String v) {
        return valueOf(v);
    }

}
