//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;




/**
 * This type specifies the value to be modified by the user during an InputRequest.
 * 
 * <p>Java class for InputValueT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputValueT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}LayoutObjectExtT">
 *       &lt;sequence>
 *         &lt;element name="InitialValue" type="{http://fdi.org/2010/client}VariantT"/>
 *         &lt;element name="Type" type="{http://fdi.org/2010/client}InputValueTypeT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputValueT", propOrder = {
    "initialValue",
    "type"
})
public class InputValueT
    extends LayoutObjectExtT
{

    @XmlElement(name = "InitialValue", required = true)
    protected VariantT initialValue;
    @XmlElement(name = "Type")
    protected InputValueTypeT type;

    /**
     * Gets the value of the initialValue property.
     * 
     * @return
     *     possible object is
     *     {@link VariantT }
     *     
     */
    public VariantT getInitialValue() {
        return initialValue;
    }

    /**
     * Sets the value of the initialValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantT }
     *     
     */
    public void setInitialValue(VariantT value) {
        this.initialValue = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link InputValueTypeT }
     *     
     */
    public InputValueTypeT getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputValueTypeT }
     *     
     */
    public void setType(InputValueTypeT value) {
        this.type = value;
    }

}
