//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * This type specifies the type of the value modified by the user during an InputRequest.
 * 
 * <p>Java class for InputValueTypeT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InputValueTypeT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="NumericType" type="{http://fdi.org/2010/client}NumericT"/>
 *         &lt;element name="StringType" type="{http://fdi.org/2010/client}StringT"/>
 *         &lt;group ref="{http://fdi.org/2010/client}SingleValueUiTemplateGroup"/>
 *         &lt;element name="DateTimeType" type="{http://fdi.org/2010/client}DateTimeT"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InputValueTypeT", propOrder = {
    "numericType",
    "stringType",
    "enumeration",
    "bitEnumeration",
    "dateTimeType"
})
public class InputValueTypeT {

    @XmlElement(name = "NumericType")
    protected NumericT numericType;
    @XmlElement(name = "StringType")
    protected StringT stringType;
    @XmlElement(name = "Enumeration")
    protected EnumerationItemListT enumeration;
    @XmlElement(name = "BitEnumeration")
    protected BitEnumerationItemList bitEnumeration;
    @XmlElement(name = "DateTimeType")
    protected DateTimeT dateTimeType;

    /**
     * Gets the value of the numericType property.
     * 
     * @return
     *     possible object is
     *     {@link NumericT }
     *     
     */
    public NumericT getNumericType() {
        return numericType;
    }

    /**
     * Sets the value of the numericType property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumericT }
     *     
     */
    public void setNumericType(NumericT value) {
        this.numericType = value;
    }

    /**
     * Gets the value of the stringType property.
     * 
     * @return
     *     possible object is
     *     {@link StringT }
     *     
     */
    public StringT getStringType() {
        return stringType;
    }

    /**
     * Sets the value of the stringType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringT }
     *     
     */
    public void setStringType(StringT value) {
        this.stringType = value;
    }

    /**
     * Gets the value of the enumeration property.
     * 
     * @return
     *     possible object is
     *     {@link EnumerationItemListT }
     *     
     */
    public EnumerationItemListT getEnumeration() {
        return enumeration;
    }

    /**
     * Sets the value of the enumeration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumerationItemListT }
     *     
     */
    public void setEnumeration(EnumerationItemListT value) {
        this.enumeration = value;
    }

    /**
     * Gets the value of the bitEnumeration property.
     * 
     * @return
     *     possible object is
     *     {@link BitEnumerationItemList }
     *     
     */
    public BitEnumerationItemList getBitEnumeration() {
        return bitEnumeration;
    }

    /**
     * Sets the value of the bitEnumeration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BitEnumerationItemList }
     *     
     */
    public void setBitEnumeration(BitEnumerationItemList value) {
        this.bitEnumeration = value;
    }

    /**
     * Gets the value of the dateTimeType property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeT }
     *     
     */
    public DateTimeT getDateTimeType() {
        return dateTimeType;
    }

    /**
     * Sets the value of the dateTimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeT }
     *     
     */
    public void setDateTimeType(DateTimeT value) {
        this.dateTimeType = value;
    }

}
