//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * This type specifies a line on a graph that indicates the normal operating range for the data displayed on the graph. Operating ranges are usually displayed via two limit lines, one for the low limit and one for the high limit.
 * 
 * <p>Java class for LimitLineT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LimitLineT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Orientation" type="{http://fdi.org/2010/client}OrientationT"/>
 *         &lt;element name="LimitValueList" type="{http://fdi.org/2010/client}VariantListT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LimitLineT", propOrder = {
    "orientation",
    "limitValueList"
})
public class LimitLineT {

    @XmlElement(name = "Orientation", required = true)
    protected OrientationT orientation;
    @XmlElement(name = "LimitValueList", required = true)
    protected VariantListT limitValueList;

    /**
     * Gets the value of the orientation property.
     * 
     * @return
     *     possible object is
     *     {@link OrientationT }
     *     
     */
    public OrientationT getOrientation() {
        return orientation;
    }

    /**
     * Sets the value of the orientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrientationT }
     *     
     */
    public void setOrientation(OrientationT value) {
        this.orientation = value;
    }

    /**
     * Gets the value of the limitValueList property.
     * 
     * @return
     *     possible object is
     *     {@link VariantListT }
     *     
     */
    public VariantListT getLimitValueList() {
        return limitValueList;
    }

    /**
     * Sets the value of the limitValueList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantListT }
     *     
     */
    public void setLimitValueList(VariantListT value) {
        this.limitValueList = value;
    }

}
