//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LineTypeT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LineTypeT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Data"/>
 *     &lt;enumeration value="Data0"/>
 *     &lt;enumeration value="Data1"/>
 *     &lt;enumeration value="Data2"/>
 *     &lt;enumeration value="Data3"/>
 *     &lt;enumeration value="Data4"/>
 *     &lt;enumeration value="Data5"/>
 *     &lt;enumeration value="Data6"/>
 *     &lt;enumeration value="Data7"/>
 *     &lt;enumeration value="Data8"/>
 *     &lt;enumeration value="Data9"/>
 *     &lt;enumeration value="LowLimit"/>
 *     &lt;enumeration value="LowLowLimit"/>
 *     &lt;enumeration value="HighLimit"/>
 *     &lt;enumeration value="HighHighLimit"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LineTypeT")
@XmlEnum
public enum LineTypeT {


    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data")
    DATA("Data"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data0")
    DATA_0("Data0"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data1")
    DATA_1("Data1"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data2")
    DATA_2("Data2"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data3")
    DATA_3("Data3"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data4")
    DATA_4("Data4"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data5")
    DATA_5("Data5"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data6")
    DATA_6("Data6"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data7")
    DATA_7("Data7"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data8")
    DATA_8("Data8"),

    /**
     * The line represents data.
     * 
     */
    @XmlEnumValue("Data9")
    DATA_9("Data9"),

    /**
     * The line represents a low limit.
     * 
     */
    @XmlEnumValue("LowLimit")
    LOW_LIMIT("LowLimit"),

    /**
     * The line represents a low low limit.
     * 
     */
    @XmlEnumValue("LowLowLimit")
    LOW_LOW_LIMIT("LowLowLimit"),

    /**
     * The line represent a high limit.
     * 
     */
    @XmlEnumValue("HighLimit")
    HIGH_LIMIT("HighLimit"),

    /**
     * The line represents a high high limit.
     * 
     */
    @XmlEnumValue("HighHighLimit")
    HIGH_HIGH_LIMIT("HighHighLimit");
    private final String value;

    LineTypeT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LineTypeT fromValue(String v) {
        for (LineTypeT c: LineTypeT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
