//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;




/**
 * <p>Java class for NumericDataT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="NumericDataT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SignedInteger"/>
 *     &lt;enumeration value="UnsignedInteger"/>
 *     &lt;enumeration value="FloatingPoint"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "NumericDataT")
@XmlEnum
public enum NumericDataT {


    /**
     * A signed integer.
     * 
     */
    @XmlEnumValue("SignedInteger")
    SIGNED_INTEGER("SignedInteger"),

    /**
     * An unsigned integer.
     * 
     */
    @XmlEnumValue("UnsignedInteger")
    UNSIGNED_INTEGER("UnsignedInteger"),

    /**
     * A floating point number.
     * 
     */
    @XmlEnumValue("FloatingPoint")
    FLOATING_POINT("FloatingPoint");
    private final String value;

    NumericDataT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static NumericDataT fromValue(String v) {
        for (NumericDataT c: NumericDataT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
