//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import javax.xml.namespace.QName;

import ae.javax.xml.bind.JAXBElement;
import ae.javax.xml.bind.annotation.XmlElementDecl;
import ae.javax.xml.bind.annotation.XmlRegistry;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.fdi._2010.client package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _LayoutItemsTAction_QNAME = new QName("http://fdi.org/2010/client", "Action");
    private final static QName _LayoutItemsTImage_QNAME = new QName("http://fdi.org/2010/client", "Image");
    private final static QName _LayoutItemsTPage_QNAME = new QName("http://fdi.org/2010/client", "Page");
    private final static QName _LayoutItemsTGrid_QNAME = new QName("http://fdi.org/2010/client", "Grid");
    private final static QName _LayoutItemsTText_QNAME = new QName("http://fdi.org/2010/client", "Text");
    private final static QName _LayoutItemsTMenu_QNAME = new QName("http://fdi.org/2010/client", "Menu");
    private final static QName _LayoutItemsTWindow_QNAME = new QName("http://fdi.org/2010/client", "Window");
    private final static QName _LayoutItemsTParameter_QNAME = new QName("http://fdi.org/2010/client", "Parameter");
    private final static QName _LayoutItemsTSeparator_QNAME = new QName("http://fdi.org/2010/client", "Separator");
    private final static QName _LayoutItemsTPlugin_QNAME = new QName("http://fdi.org/2010/client", "Plugin");
    private final static QName _LayoutItemsTGraph_QNAME = new QName("http://fdi.org/2010/client", "Graph");
    private final static QName _LayoutItemsTChart_QNAME = new QName("http://fdi.org/2010/client", "Chart");
    private final static QName _LayoutItemsTEditDisplay_QNAME = new QName("http://fdi.org/2010/client", "EditDisplay");
    private final static QName _LayoutItemsTGroup_QNAME = new QName("http://fdi.org/2010/client", "Group");
    private final static QName _LayoutItemsTRowBreak_QNAME = new QName("http://fdi.org/2010/client", "RowBreak");
    private final static QName _LayoutItemsTTable_QNAME = new QName("http://fdi.org/2010/client", "Table");
    private final static QName _LayoutItemsTDialog_QNAME = new QName("http://fdi.org/2010/client", "Dialog");
    private final static QName _LayoutItemsTColumnBreak_QNAME = new QName("http://fdi.org/2010/client", "ColumnBreak");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.fdi._2010.client
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link UidLayoutInformation }
     * 
     */
    public UidLayoutInformation createUidLayoutInformation() {
        return new UidLayoutInformation();
    }

    /**
     * Create an instance of {@link PageT }
     * 
     */
    public PageT createPageT() {
        return new PageT();
    }

    /**
     * Create an instance of {@link MenuT }
     * 
     */
    public MenuT createMenuT() {
        return new MenuT();
    }

    /**
     * Create an instance of {@link ChartT }
     * 
     */
    public ChartT createChartT() {
        return new ChartT();
    }

    /**
     * Create an instance of {@link PluginT }
     * 
     */
    public PluginT createPluginT() {
        return new PluginT();
    }

    /**
     * Create an instance of {@link GraphT }
     * 
     */
    public GraphT createGraphT() {
        return new GraphT();
    }

    /**
     * Create an instance of {@link SelectableItemT }
     * 
     */
    public SelectableItemT createSelectableItemT() {
        return new SelectableItemT();
    }

    /**
     * Create an instance of {@link VectorListT }
     * 
     */
    public VectorListT createVectorListT() {
        return new VectorListT();
    }

    /**
     * Create an instance of {@link VariantT }
     * 
     */
    public VariantT createVariantT() {
        return new VariantT();
    }

    /**
     * Create an instance of {@link SelectionRequestT }
     * 
     */
    public SelectionRequestT createSelectionRequestT() {
        return new SelectionRequestT();
    }

    /**
     * Create an instance of {@link DelayMessageRequestT }
     * 
     */
    public DelayMessageRequestT createDelayMessageRequestT() {
        return new DelayMessageRequestT();
    }

    /**
     * Create an instance of {@link PointT }
     * 
     */
    public PointT createPointT() {
        return new PointT();
    }

    /**
     * Create an instance of {@link VariantListT }
     * 
     */
    public VariantListT createVariantListT() {
        return new VariantListT();
    }

    /**
     * Create an instance of {@link RangeT }
     * 
     */
    public RangeT createRangeT() {
        return new RangeT();
    }

    /**
     * Create an instance of {@link LimitLineT }
     * 
     */
    public LimitLineT createLimitLineT() {
        return new LimitLineT();
    }

    /**
     * Create an instance of {@link InfoRequestT }
     * 
     */
    public InfoRequestT createInfoRequestT() {
        return new InfoRequestT();
    }

    /**
     * Create an instance of {@link EditDisplayT }
     * 
     */
    public EditDisplayT createEditDisplayT() {
        return new EditDisplayT();
    }

    /**
     * Create an instance of {@link LayoutItemsT }
     * 
     */
    public LayoutItemsT createLayoutItemsT() {
        return new LayoutItemsT();
    }

    /**
     * Create an instance of {@link ParameterT }
     * 
     */
    public ParameterT createParameterT() {
        return new ParameterT();
    }

    /**
     * Create an instance of {@link PointListT }
     * 
     */
    public PointListT createPointListT() {
        return new PointListT();
    }

    /**
     * Create an instance of {@link MenuT.ItemList }
     * 
     */
    public MenuT.ItemList createMenuTItemList() {
        return new MenuT.ItemList();
    }

    /**
     * Create an instance of {@link ImageT.Link }
     * 
     */
    public ImageT.Link createImageTLink() {
        return new ImageT.Link();
    }

    /**
     * Create an instance of {@link SourceT }
     * 
     */
    public SourceT createSourceT() {
        return new SourceT();
    }

    /**
     * Create an instance of {@link EnumerationItemListT }
     * 
     */
    public EnumerationItemListT createEnumerationItemListT() {
        return new EnumerationItemListT();
    }

    /**
     * Create an instance of {@link SourceListT }
     * 
     */
    public SourceListT createSourceListT() {
        return new SourceListT();
    }

    /**
     * Create an instance of {@link DateTimeT }
     * 
     */
    public DateTimeT createDateTimeT() {
        return new DateTimeT();
    }

    /**
     * Create an instance of {@link BreakT }
     * 
     */
    public BreakT createBreakT() {
        return new BreakT();
    }

    /**
     * Create an instance of {@link PresetValueListT }
     * 
     */
    public PresetValueListT createPresetValueListT() {
        return new PresetValueListT();
    }

    /**
     * Create an instance of {@link TableT.ItemList }
     * 
     */
    public TableT.ItemList createTableTItemList() {
        return new TableT.ItemList();
    }

    /**
     * Create an instance of {@link UiTemplateT }
     * 
     */
    public UiTemplateT createUiTemplateT() {
        return new UiTemplateT();
    }

    /**
     * Create an instance of {@link UiTemplateT.MultiValueUiTemplate }
     * 
     */
    public UiTemplateT.MultiValueUiTemplate createUiTemplateTMultiValueUiTemplate() {
        return new UiTemplateT.MultiValueUiTemplate();
    }

    /**
     * Create an instance of {@link InputValueT }
     * 
     */
    public InputValueT createInputValueT() {
        return new InputValueT();
    }

    /**
     * Create an instance of {@link DialogT }
     * 
     */
    public DialogT createDialogT() {
        return new DialogT();
    }

    /**
     * Create an instance of {@link WindowT }
     * 
     */
    public WindowT createWindowT() {
        return new WindowT();
    }

    /**
     * Create an instance of {@link InputRequestT }
     * 
     */
    public InputRequestT createInputRequestT() {
        return new InputRequestT();
    }

    /**
     * Create an instance of {@link GroupT }
     * 
     */
    public GroupT createGroupT() {
        return new GroupT();
    }

    /**
     * Create an instance of {@link VectorT }
     * 
     */
    public VectorT createVectorT() {
        return new VectorT();
    }

    /**
     * Create an instance of {@link AbortRequestT }
     * 
     */
    public AbortRequestT createAbortRequestT() {
        return new AbortRequestT();
    }

    /**
     * Create an instance of {@link ButtonListT }
     * 
     */
    public ButtonListT createButtonListT() {
        return new ButtonListT();
    }

    /**
     * Create an instance of {@link ImageT }
     * 
     */
    public ImageT createImageT() {
        return new ImageT();
    }

    /**
     * Create an instance of {@link ResponseT }
     * 
     */
    public ResponseT createResponseT() {
        return new ResponseT();
    }

    /**
     * Create an instance of {@link BitEnumerationItemT }
     * 
     */
    public BitEnumerationItemT createBitEnumerationItemT() {
        return new BitEnumerationItemT();
    }

    /**
     * Create an instance of {@link RangeListT }
     * 
     */
    public RangeListT createRangeListT() {
        return new RangeListT();
    }

    /**
     * Create an instance of {@link TableT }
     * 
     */
    public TableT createTableT() {
        return new TableT();
    }

    /**
     * Create an instance of {@link PresetValueT }
     * 
     */
    public PresetValueT createPresetValueT() {
        return new PresetValueT();
    }

    /**
     * Create an instance of {@link ParameterListT }
     * 
     */
    public ParameterListT createParameterListT() {
        return new ParameterListT();
    }

    /**
     * Create an instance of {@link GroupT.ItemList }
     * 
     */
    public GroupT.ItemList createGroupTItemList() {
        return new GroupT.ItemList();
    }

    /**
     * Create an instance of {@link WindowT.ItemList }
     * 
     */
    public WindowT.ItemList createWindowTItemList() {
        return new WindowT.ItemList();
    }

    /**
     * Create an instance of {@link BitEnumerationItemList }
     * 
     */
    public BitEnumerationItemList createBitEnumerationItemList() {
        return new BitEnumerationItemList();
    }

    /**
     * Create an instance of {@link PageT.ItemList }
     * 
     */
    public PageT.ItemList createPageTItemList() {
        return new PageT.ItemList();
    }

    /**
     * Create an instance of {@link IndexListT }
     * 
     */
    public IndexListT createIndexListT() {
        return new IndexListT();
    }

    /**
     * Create an instance of {@link AxisT }
     * 
     */
    public AxisT createAxisT() {
        return new AxisT();
    }

    /**
     * Create an instance of {@link InputValueTypeT }
     * 
     */
    public InputValueTypeT createInputValueTypeT() {
        return new InputValueTypeT();
    }

    /**
     * Create an instance of {@link AcknowledgementRequestT }
     * 
     */
    public AcknowledgementRequestT createAcknowledgementRequestT() {
        return new AcknowledgementRequestT();
    }

    /**
     * Create an instance of {@link GridT }
     * 
     */
    public GridT createGridT() {
        return new GridT();
    }

    /**
     * Create an instance of {@link WaveformListT }
     * 
     */
    public WaveformListT createWaveformListT() {
        return new WaveformListT();
    }

    /**
     * Create an instance of {@link DialogT.ItemList }
     * 
     */
    public DialogT.ItemList createDialogTItemList() {
        return new DialogT.ItemList();
    }

    /**
     * Create an instance of {@link NumericT }
     * 
     */
    public NumericT createNumericT() {
        return new NumericT();
    }

    /**
     * Create an instance of {@link ActionListT }
     * 
     */
    public ActionListT createActionListT() {
        return new ActionListT();
    }

    /**
     * Create an instance of {@link StringT }
     * 
     */
    public StringT createStringT() {
        return new StringT();
    }

    /**
     * Create an instance of {@link ActionResponseT }
     * 
     */
    public ActionResponseT createActionResponseT() {
        return new ActionResponseT();
    }

    /**
     * Create an instance of {@link VectorT.Items }
     * 
     */
    public VectorT.Items createVectorTItems() {
        return new VectorT.Items();
    }

    /**
     * Create an instance of {@link UidRequestT }
     * 
     */
    public UidRequestT createUidRequestT() {
        return new UidRequestT();
    }

    /**
     * Create an instance of {@link ActionT }
     * 
     */
    public ActionT createActionT() {
        return new ActionT();
    }

    /**
     * Create an instance of {@link LimitLineListT }
     * 
     */
    public LimitLineListT createLimitLineListT() {
        return new LimitLineListT();
    }

    /**
     * Create an instance of {@link InputResponseT }
     * 
     */
    public InputResponseT createInputResponseT() {
        return new InputResponseT();
    }

    /**
     * Create an instance of {@link ActionRequestT }
     * 
     */
    public ActionRequestT createActionRequestT() {
        return new ActionRequestT();
    }

    /**
     * Create an instance of {@link EnumerationItemT }
     * 
     */
    public EnumerationItemT createEnumerationItemT() {
        return new EnumerationItemT();
    }

    /**
     * Create an instance of {@link OptionListT }
     * 
     */
    public OptionListT createOptionListT() {
        return new OptionListT();
    }

    /**
     * Create an instance of {@link WaveformT }
     * 
     */
    public WaveformT createWaveformT() {
        return new WaveformT();
    }

    /**
     * Create an instance of {@link SelectionResponseT }
     * 
     */
    public SelectionResponseT createSelectionResponseT() {
        return new SelectionResponseT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Action", scope = LayoutItemsT.class)
    public JAXBElement<ActionT> createLayoutItemsTAction(ActionT value) {
        return new JAXBElement<ActionT>(_LayoutItemsTAction_QNAME, ActionT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Image", scope = LayoutItemsT.class)
    public JAXBElement<ImageT> createLayoutItemsTImage(ImageT value) {
        return new JAXBElement<ImageT>(_LayoutItemsTImage_QNAME, ImageT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PageT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Page", scope = LayoutItemsT.class)
    public JAXBElement<PageT> createLayoutItemsTPage(PageT value) {
        return new JAXBElement<PageT>(_LayoutItemsTPage_QNAME, PageT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GridT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Grid", scope = LayoutItemsT.class)
    public JAXBElement<GridT> createLayoutItemsTGrid(GridT value) {
        return new JAXBElement<GridT>(_LayoutItemsTGrid_QNAME, GridT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Text", scope = LayoutItemsT.class)
    public JAXBElement<String> createLayoutItemsTText(String value) {
        return new JAXBElement<String>(_LayoutItemsTText_QNAME, String.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MenuT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Menu", scope = LayoutItemsT.class)
    public JAXBElement<MenuT> createLayoutItemsTMenu(MenuT value) {
        return new JAXBElement<MenuT>(_LayoutItemsTMenu_QNAME, MenuT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WindowT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Window", scope = LayoutItemsT.class)
    public JAXBElement<WindowT> createLayoutItemsTWindow(WindowT value) {
        return new JAXBElement<WindowT>(_LayoutItemsTWindow_QNAME, WindowT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ParameterT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Parameter", scope = LayoutItemsT.class)
    public JAXBElement<ParameterT> createLayoutItemsTParameter(ParameterT value) {
        return new JAXBElement<ParameterT>(_LayoutItemsTParameter_QNAME, ParameterT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreakT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Separator", scope = LayoutItemsT.class)
    public JAXBElement<BreakT> createLayoutItemsTSeparator(BreakT value) {
        return new JAXBElement<BreakT>(_LayoutItemsTSeparator_QNAME, BreakT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PluginT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Plugin", scope = LayoutItemsT.class)
    public JAXBElement<PluginT> createLayoutItemsTPlugin(PluginT value) {
        return new JAXBElement<PluginT>(_LayoutItemsTPlugin_QNAME, PluginT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GraphT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Graph", scope = LayoutItemsT.class)
    public JAXBElement<GraphT> createLayoutItemsTGraph(GraphT value) {
        return new JAXBElement<GraphT>(_LayoutItemsTGraph_QNAME, GraphT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChartT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Chart", scope = LayoutItemsT.class)
    public JAXBElement<ChartT> createLayoutItemsTChart(ChartT value) {
        return new JAXBElement<ChartT>(_LayoutItemsTChart_QNAME, ChartT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditDisplayT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "EditDisplay", scope = LayoutItemsT.class)
    public JAXBElement<EditDisplayT> createLayoutItemsTEditDisplay(EditDisplayT value) {
        return new JAXBElement<EditDisplayT>(_LayoutItemsTEditDisplay_QNAME, EditDisplayT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GroupT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Group", scope = LayoutItemsT.class)
    public JAXBElement<GroupT> createLayoutItemsTGroup(GroupT value) {
        return new JAXBElement<GroupT>(_LayoutItemsTGroup_QNAME, GroupT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreakT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "RowBreak", scope = LayoutItemsT.class)
    public JAXBElement<BreakT> createLayoutItemsTRowBreak(BreakT value) {
        return new JAXBElement<BreakT>(_LayoutItemsTRowBreak_QNAME, BreakT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TableT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Table", scope = LayoutItemsT.class)
    public JAXBElement<TableT> createLayoutItemsTTable(TableT value) {
        return new JAXBElement<TableT>(_LayoutItemsTTable_QNAME, TableT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DialogT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "Dialog", scope = LayoutItemsT.class)
    public JAXBElement<DialogT> createLayoutItemsTDialog(DialogT value) {
        return new JAXBElement<DialogT>(_LayoutItemsTDialog_QNAME, DialogT.class, LayoutItemsT.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BreakT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://fdi.org/2010/client", name = "ColumnBreak", scope = LayoutItemsT.class)
    public JAXBElement<BreakT> createLayoutItemsTColumnBreak(BreakT value) {
        return new JAXBElement<BreakT>(_LayoutItemsTColumnBreak_QNAME, BreakT.class, LayoutItemsT.class, value);
    }

}
