//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//

@ae.javax.xml.bind.annotation.XmlSchema(namespace = "http://fdi.org/2010/client", elementFormDefault = ae.javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.fdi._2010.client;

