//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlAttribute;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * This type specifies a device or block parameter that is displayed in a user interface element such as a Window or Dialog.
 * 
 * <p>Java class for ParameterT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ParameterT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}LayoutObjectExtT">
 *       &lt;sequence>
 *         &lt;element name="UITemplate" type="{http://fdi.org/2010/client}UiTemplateT" minOccurs="0"/>
 *         &lt;element name="SubindexList" type="{http://fdi.org/2010/client}IndexListT" minOccurs="0"/>
 *         &lt;element name="Units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsDynamic" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="Handling" type="{http://fdi.org/2010/client}HandlingT" minOccurs="0"/>
 *         &lt;element name="RangeList" type="{http://fdi.org/2010/client}RangeListT" minOccurs="0"/>
 *         &lt;element name="DisplayFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EditFormat" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DisplayLabel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DisplayValue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="DisplayUnits" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="PreEditActionList" type="{http://fdi.org/2010/client}ActionListT" minOccurs="0"/>
 *         &lt;element name="PostEditActionList" type="{http://fdi.org/2010/client}ActionListT" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="NodeId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ParameterT", propOrder = {
    "uiTemplate",
    "subindexList",
    "units",
    "isDynamic",
    "handling",
    "rangeList",
    "displayFormat",
    "editFormat",
    "displayLabel",
    "displayValue",
    "displayUnits",
    "preEditActionList",
    "postEditActionList"
})
public class ParameterT
    extends LayoutObjectExtT
{

    @XmlElement(name = "UITemplate")
    protected UiTemplateT uiTemplate;
    @XmlElement(name = "SubindexList")
    protected IndexListT subindexList;
    @XmlElement(name = "Units")
    protected String units;
    @XmlElement(name = "IsDynamic")
    protected Boolean isDynamic;
    @XmlElement(name = "Handling")
    protected HandlingT handling;
    @XmlElement(name = "RangeList")
    protected RangeListT rangeList;
    @XmlElement(name = "DisplayFormat")
    protected String displayFormat;
    @XmlElement(name = "EditFormat")
    protected String editFormat;
    @XmlElement(name = "DisplayLabel")
    protected Boolean displayLabel;
    @XmlElement(name = "DisplayValue")
    protected Boolean displayValue;
    @XmlElement(name = "DisplayUnits")
    protected Boolean displayUnits;
    @XmlElement(name = "PreEditActionList")
    protected ActionListT preEditActionList;
    @XmlElement(name = "PostEditActionList")
    protected ActionListT postEditActionList;
    @XmlAttribute(name = "NodeId", required = true)
    protected String nodeId;

    /**
     * Gets the value of the uiTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link UiTemplateT }
     *     
     */
    public UiTemplateT getUITemplate() {
        return uiTemplate;
    }

    /**
     * Sets the value of the uiTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiTemplateT }
     *     
     */
    public void setUITemplate(UiTemplateT value) {
        this.uiTemplate = value;
    }

    /**
     * Gets the value of the subindexList property.
     * 
     * @return
     *     possible object is
     *     {@link IndexListT }
     *     
     */
    public IndexListT getSubindexList() {
        return subindexList;
    }

    /**
     * Sets the value of the subindexList property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndexListT }
     *     
     */
    public void setSubindexList(IndexListT value) {
        this.subindexList = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the isDynamic property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDynamic() {
        return isDynamic;
    }

    /**
     * Sets the value of the isDynamic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDynamic(Boolean value) {
        this.isDynamic = value;
    }

    /**
     * Gets the value of the handling property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingT }
     *     
     */
    public HandlingT getHandling() {
        return handling;
    }

    /**
     * Sets the value of the handling property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingT }
     *     
     */
    public void setHandling(HandlingT value) {
        this.handling = value;
    }

    /**
     * Gets the value of the rangeList property.
     * 
     * @return
     *     possible object is
     *     {@link RangeListT }
     *     
     */
    public RangeListT getRangeList() {
        return rangeList;
    }

    /**
     * Sets the value of the rangeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RangeListT }
     *     
     */
    public void setRangeList(RangeListT value) {
        this.rangeList = value;
    }

    /**
     * Gets the value of the displayFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayFormat() {
        return displayFormat;
    }

    /**
     * Sets the value of the displayFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayFormat(String value) {
        this.displayFormat = value;
    }

    /**
     * Gets the value of the editFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditFormat() {
        return editFormat;
    }

    /**
     * Sets the value of the editFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditFormat(String value) {
        this.editFormat = value;
    }

    /**
     * Gets the value of the displayLabel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayLabel() {
        return displayLabel;
    }

    /**
     * Sets the value of the displayLabel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayLabel(Boolean value) {
        this.displayLabel = value;
    }

    /**
     * Gets the value of the displayValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayValue() {
        return displayValue;
    }

    /**
     * Sets the value of the displayValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayValue(Boolean value) {
        this.displayValue = value;
    }

    /**
     * Gets the value of the displayUnits property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisplayUnits() {
        return displayUnits;
    }

    /**
     * Sets the value of the displayUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisplayUnits(Boolean value) {
        this.displayUnits = value;
    }

    /**
     * Gets the value of the preEditActionList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionListT }
     *     
     */
    public ActionListT getPreEditActionList() {
        return preEditActionList;
    }

    /**
     * Sets the value of the preEditActionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionListT }
     *     
     */
    public void setPreEditActionList(ActionListT value) {
        this.preEditActionList = value;
    }

    /**
     * Gets the value of the postEditActionList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionListT }
     *     
     */
    public ActionListT getPostEditActionList() {
        return postEditActionList;
    }

    /**
     * Sets the value of the postEditActionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionListT }
     *     
     */
    public void setPostEditActionList(ActionListT value) {
        this.postEditActionList = value;
    }

    /**
     * Gets the value of the nodeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNodeId() {
        return nodeId;
    }

    /**
     * Sets the value of the nodeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNodeId(String value) {
        this.nodeId = value;
    }

}
