//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * This type specifies a position in two-dimensional space.
 * 
 * <p>Java class for PointT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PointT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="X" type="{http://fdi.org/2010/client}VariantT"/>
 *         &lt;element name="Y" type="{http://fdi.org/2010/client}VariantT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PointT", propOrder = {
    "x",
    "y"
})
public class PointT {

    @XmlElement(name = "X", required = true)
    protected VariantT x;
    @XmlElement(name = "Y", required = true)
    protected VariantT y;

    /**
     * Gets the value of the x property.
     * 
     * @return
     *     possible object is
     *     {@link VariantT }
     *     
     */
    public VariantT getX() {
        return x;
    }

    /**
     * Sets the value of the x property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantT }
     *     
     */
    public void setX(VariantT value) {
        this.x = value;
    }

    /**
     * Gets the value of the y property.
     * 
     * @return
     *     possible object is
     *     {@link VariantT }
     *     
     */
    public VariantT getY() {
        return y;
    }

    /**
     * Sets the value of the y property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariantT }
     *     
     */
    public void setY(VariantT value) {
        this.y = value;
    }

}
