//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * This type specifies a request sent from an FDI Server to an FDI Client when the user needs choose from a list of options during an Action. Once the user has selected one of the options, the FDI Client sends an SelectionResponse back to the FDI Server.
 * 
 * <p>Java class for SelectionRequestT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectionRequestT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Prompt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OptionList" type="{http://fdi.org/2010/client}OptionListT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectionRequestT", propOrder = {
    "prompt",
    "optionList"
})
public class SelectionRequestT {

    @XmlElement(name = "Prompt", required = true)
    protected String prompt;
    @XmlElement(name = "OptionList", required = true)
    protected OptionListT optionList;

    /**
     * Gets the value of the prompt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * Sets the value of the prompt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrompt(String value) {
        this.prompt = value;
    }

    /**
     * Gets the value of the optionList property.
     * 
     * @return
     *     possible object is
     *     {@link OptionListT }
     *     
     */
    public OptionListT getOptionList() {
        return optionList;
    }

    /**
     * Sets the value of the optionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptionListT }
     *     
     */
    public void setOptionList(OptionListT value) {
        this.optionList = value;
    }

}
