//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * This type specifies a source of data values displayed by a chart.
 * 
 * <p>Java class for SourceT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}AbstractSourceT">
 *       &lt;sequence>
 *         &lt;element name="ParameterList" type="{http://fdi.org/2010/client}ParameterListT"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceT", propOrder = {
    "parameterList"
})
public class SourceT
    extends AbstractSourceT
{

    @XmlElement(name = "ParameterList", required = true)
    protected ParameterListT parameterList;

    /**
     * Gets the value of the parameterList property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterListT }
     *     
     */
    public ParameterListT getParameterList() {
        return parameterList;
    }

    /**
     * Sets the value of the parameterList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterListT }
     *     
     */
    public void setParameterList(ParameterListT value) {
        this.parameterList = value;
    }

}
