//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlEnum;
import ae.javax.xml.bind.annotation.XmlEnumValue;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * <p>Java class for StringDataT.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StringDataT">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ASCII"/>
 *     &lt;enumeration value="UTF8"/>
 *     &lt;enumeration value="Hexadecimal"/>
 *     &lt;enumeration value="Bitstring"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StringDataT")
@XmlEnum
public enum StringDataT {


    /**
     * String of ASCII characters.
     * 
     */
    ASCII("ASCII"),

    /**
     * String of Unicode characters encoded in UTF-8 format.
     * 
     */
    @XmlEnumValue("UTF8")
    UTF_8("UTF8"),

    /**
     * Binary data represented as hexadecimal digits.
     * 
     */
    @XmlEnumValue("Hexadecimal")
    HEXADECIMAL("Hexadecimal"),

    /**
     * Binary data represented as string of binary digits.
     * 
     */
    @XmlEnumValue("Bitstring")
    BITSTRING("Bitstring");
    private final String value;

    StringDataT(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static StringDataT fromValue(String v) {
        for (StringDataT c: StringDataT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
