//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * This type specifies a request sent from an FDI Server to an FDI Client when when an advanced user interface needs to be shown to the user during an Action. The structure of the user interface is specified as a Dialog, Table, or Window. When the user interface is no longer needed, the FDI Client sends a UIDResponse back to the FDI Server.
 * 
 * <p>Java class for UidRequestT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UidRequestT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="UidRef" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ButtonList" type="{http://fdi.org/2010/client}ButtonListT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UidRequestT", propOrder = {
    "uidRef",
    "buttonList"
})
public class UidRequestT {

    @XmlElement(name = "UidRef", required = true)
    protected String uidRef;
    @XmlElement(name = "ButtonList", required = true)
    protected ButtonListT buttonList;

    /**
     * Gets the value of the uidRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUidRef() {
        return uidRef;
    }

    /**
     * Sets the value of the uidRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUidRef(String value) {
        this.uidRef = value;
    }

    /**
     * Gets the value of the buttonList property.
     * 
     * @return
     *     possible object is
     *     {@link ButtonListT }
     *     
     */
    public ButtonListT getButtonList() {
        return buttonList;
    }

    /**
     * Sets the value of the buttonList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ButtonListT }
     *     
     */
    public void setButtonList(ButtonListT value) {
        this.buttonList = value;
    }

}
