//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import java.util.ArrayList;
import java.util.List;
import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlSchemaType;
import ae.javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UiTemplateT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UiTemplateT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;group ref="{http://fdi.org/2010/client}SingleValueUiTemplateGroup"/>
 *         &lt;element name="MultiValueUiTemplate">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Dimension" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
 *                   &lt;group ref="{http://fdi.org/2010/client}SingleValueUiTemplateGroup" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UiTemplateT", propOrder = {
    "enumeration",
    "bitEnumeration",
    "multiValueUiTemplate"
})
public class UiTemplateT {

    @XmlElement(name = "Enumeration")
    protected EnumerationItemListT enumeration;
    @XmlElement(name = "BitEnumeration")
    protected BitEnumerationItemList bitEnumeration;
    @XmlElement(name = "MultiValueUiTemplate")
    protected UiTemplateT.MultiValueUiTemplate multiValueUiTemplate;

    /**
     * Gets the value of the enumeration property.
     * 
     * @return
     *     possible object is
     *     {@link EnumerationItemListT }
     *     
     */
    public EnumerationItemListT getEnumeration() {
        return enumeration;
    }

    /**
     * Sets the value of the enumeration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnumerationItemListT }
     *     
     */
    public void setEnumeration(EnumerationItemListT value) {
        this.enumeration = value;
    }

    /**
     * Gets the value of the bitEnumeration property.
     * 
     * @return
     *     possible object is
     *     {@link BitEnumerationItemList }
     *     
     */
    public BitEnumerationItemList getBitEnumeration() {
        return bitEnumeration;
    }

    /**
     * Sets the value of the bitEnumeration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BitEnumerationItemList }
     *     
     */
    public void setBitEnumeration(BitEnumerationItemList value) {
        this.bitEnumeration = value;
    }

    /**
     * Gets the value of the multiValueUiTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link UiTemplateT.MultiValueUiTemplate }
     *     
     */
    public UiTemplateT.MultiValueUiTemplate getMultiValueUiTemplate() {
        return multiValueUiTemplate;
    }

    /**
     * Sets the value of the multiValueUiTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link UiTemplateT.MultiValueUiTemplate }
     *     
     */
    public void setMultiValueUiTemplate(UiTemplateT.MultiValueUiTemplate value) {
        this.multiValueUiTemplate = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Dimension" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" maxOccurs="unbounded"/>
     *         &lt;group ref="{http://fdi.org/2010/client}SingleValueUiTemplateGroup" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dimension",
        "enumeration",
        "bitEnumeration"
    })
    public static class MultiValueUiTemplate {

        @XmlElement(name = "Dimension", type = Long.class)
        @XmlSchemaType(name = "unsignedInt")
        protected List<Long> dimension;
        @XmlElement(name = "Enumeration")
        protected EnumerationItemListT enumeration;
        @XmlElement(name = "BitEnumeration")
        protected BitEnumerationItemList bitEnumeration;

        /**
         * Gets the value of the dimension property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dimension property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDimension().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Long }
         * 
         * 
         */
        public List<Long> getDimension() {
            if (dimension == null) {
                dimension = new ArrayList<Long>();
            }
            return this.dimension;
        }

        /**
         * Gets the value of the enumeration property.
         * 
         * @return
         *     possible object is
         *     {@link EnumerationItemListT }
         *     
         */
        public EnumerationItemListT getEnumeration() {
            return enumeration;
        }

        /**
         * Sets the value of the enumeration property.
         * 
         * @param value
         *     allowed object is
         *     {@link EnumerationItemListT }
         *     
         */
        public void setEnumeration(EnumerationItemListT value) {
            this.enumeration = value;
        }

        /**
         * Gets the value of the bitEnumeration property.
         * 
         * @return
         *     possible object is
         *     {@link BitEnumerationItemList }
         *     
         */
        public BitEnumerationItemList getBitEnumeration() {
            return bitEnumeration;
        }

        /**
         * Sets the value of the bitEnumeration property.
         * 
         * @param value
         *     allowed object is
         *     {@link BitEnumerationItemList }
         *     
         */
        public void setBitEnumeration(BitEnumerationItemList value) {
            this.bitEnumeration = value;
        }

    }

}
