//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.19 at 03:00:30 PM MEZ 
//


package org.fdi._2010.client;

import ae.javax.xml.bind.annotation.XmlAccessType;
import ae.javax.xml.bind.annotation.XmlAccessorType;
import ae.javax.xml.bind.annotation.XmlElement;
import ae.javax.xml.bind.annotation.XmlType;



/**
 * This type specifies a single data set displayed by on a graph. A graph may contain one or more waveforms.
 * 
 * <p>Java class for WaveformT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WaveformT">
 *   &lt;complexContent>
 *     &lt;extension base="{http://fdi.org/2010/client}AbstractSourceT">
 *       &lt;sequence>
 *         &lt;element name="Handling" type="{http://fdi.org/2010/client}HandlingT" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="LimitLineList" type="{http://fdi.org/2010/client}LimitLineListT"/>
 *           &lt;element name="ListOfDataPoints" type="{http://fdi.org/2010/client}PointListT"/>
 *         &lt;/choice>
 *         &lt;element name="KeyPointList" type="{http://fdi.org/2010/client}PointListT" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WaveformT", propOrder = {
    "handling",
    "limitLineList",
    "listOfDataPoints",
    "keyPointList"
})
public class WaveformT
    extends AbstractSourceT
{

    @XmlElement(name = "Handling")
    protected HandlingT handling;
    @XmlElement(name = "LimitLineList")
    protected LimitLineListT limitLineList;
    @XmlElement(name = "ListOfDataPoints")
    protected PointListT listOfDataPoints;
    @XmlElement(name = "KeyPointList")
    protected PointListT keyPointList;

    /**
     * Gets the value of the handling property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingT }
     *     
     */
    public HandlingT getHandling() {
        return handling;
    }

    /**
     * Sets the value of the handling property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingT }
     *     
     */
    public void setHandling(HandlingT value) {
        this.handling = value;
    }

    /**
     * Gets the value of the limitLineList property.
     * 
     * @return
     *     possible object is
     *     {@link LimitLineListT }
     *     
     */
    public LimitLineListT getLimitLineList() {
        return limitLineList;
    }

    /**
     * Sets the value of the limitLineList property.
     * 
     * @param value
     *     allowed object is
     *     {@link LimitLineListT }
     *     
     */
    public void setLimitLineList(LimitLineListT value) {
        this.limitLineList = value;
    }

    /**
     * Gets the value of the listOfDataPoints property.
     * 
     * @return
     *     possible object is
     *     {@link PointListT }
     *     
     */
    public PointListT getListOfDataPoints() {
        return listOfDataPoints;
    }

    /**
     * Sets the value of the listOfDataPoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointListT }
     *     
     */
    public void setListOfDataPoints(PointListT value) {
        this.listOfDataPoints = value;
    }

    /**
     * Gets the value of the keyPointList property.
     * 
     * @return
     *     possible object is
     *     {@link PointListT }
     *     
     */
    public PointListT getKeyPointList() {
        return keyPointList;
    }

    /**
     * Sets the value of the keyPointList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointListT }
     *     
     */
    public void setKeyPointList(PointListT value) {
        this.keyPointList = value;
    }

}
